name: graphgen
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - cudatoolkit=11.3
  - pytorch=1.12
#  - torchaudio
  - torchvision
  - jupyterlab
  - networkx
  - matplotlib
  - scikit-learn
  - python-louvain
  - tensorboard
